overblog_graphql:
    definitions:
        show_debug_info: true
        schema:
            query: Query
            mutation: Mutation
            types: ["DateTime"]
        mappings:
            auto_discover: false
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: ~
#    errors_handler: false
