Comment:
  type: object
  config:
    description: "The Comment type."
    fields:
      id:
        type: "ID!"
      content:
        type: "String!"
      published_date:
        type: "DateTime!"
      author:
        type: "User"
      shirt:
        type: "Shirt"
    interfaces: ["Node"]

CommentConnection:
  type: relay-connection
  config:
    nodeType: "Comment"
