Comment:
  type: object
  config:
    description: "The Comment type."
    fields:
      id:
        type: "ID!"
      content:
        type: "String!"
      published_date:
        type: "DateTime!"
      author:
        type: "User"
      shirt:
        type: "Shirt"
    interfaces: ["Node"]

CommentConnection:
  type: relay-connection
  config:
    nodeType: "Comment"

commentPayload:
  type: relay-mutation-payload
  config:
    fields:
      id:
        type: "ID!"
      content:
        type: "String!"
      published_date:
        type: "DateTime!"
      author:
        type: "User"
      shirt:
        type: "Shirt"

createCommentInput:
  type: relay-mutation-input
  config:
    fields:
      content:
        type: "String!"
      shirtID:
        type: "ID!"

updateCommentInput:
  type: relay-mutation-input
  config:
    fields:
      id:
        type: "ID!"
      content:
        type: "String!"

deleteCommentPayload:
  type: relay-mutation-payload
  config:
    fields:
      id:
        type: "ID!"

deleteCommentInput:
  type: relay-mutation-input
  config:
    fields:
      id:
        type: "ID!"
