Mutation:
  type: object
  config:
    description: "The Root Mutation type."
    fields:
      # Create a user field
      createUser:
        description: "Create a User."
        builder: "Relay::Mutation"
        builderConfig:
          inputType: "createUserInput"
          payloadType: "userPayload"
          mutateAndGetPayload: "@=mutation('create_user', [value])"
      # Update a user field
      updateUser:
        description: "Update a User."
        builder: "Relay::Mutation"
        builderConfig:
          inputType: "updateUserInput"
          payloadType: "userPayload"
          mutateAndGetPayload: "@=mutation('update_user', [value])"
      # Delete a user field
      deleteUser:
        description: "Delete a User."
        builder: "Relay::Mutation"
        builderConfig:
          inputType: "deleteUserInput"
          payloadType: "deleteUserPayload"
          mutateAndGetPayload: "@=mutation('delete_user', [value])"

      # Create a single shirt
      createShirt:
        description: "Create a Shirt."
        builder: "Relay::Mutation"
        builderConfig:
          inputType: "createShirtInput"
          payloadType: "shirtPayload"
          mutateAndGetPayload: "@=mutation('create_shirt', [value])"
      # Update a single shirt
      updateShirt:
        description: "Update a Shirt."
        builder: "Relay::Mutation"
        builderConfig:
          inputType: "updateShirtInput"
          payloadType: "shirtPayload"
          mutateAndGetPayload: "@=mutation('update_shirt', [value])"
      # Delete s single Shirt
      deleteShirt:
        description: "Delete a Shirt."
        builder: "Relay::Mutation"
        builderConfig:
          inputType: "deleteShirtInput"
          payloadType: "deleteShirtPayload"
          mutateAndGetPayload: "@=mutation('delete_shirt', [value])"

      # Create a single Comment
      createComment:
        description: "Create a Comment."
        builder: "Relay::Mutation"
        builderConfig:
          inputType: "createCommentInput"
          payloadType: "commentPayload"
          mutateAndGetPayload: "@=mutation('create_comment', [value])"
      # Update a single Comment
      updateComment:
        description: "Update a Comment."
        builder: "Relay::Mutation"
        builderConfig:
          inputType: "updateCommentInput"
          payloadType: "commentPayload"
          mutateAndGetPayload: "@=mutation('update_comment', [value])"
      # Delete s single Comment
      deleteComment:
        description: "Delete a Comment."
        builder: "Relay::Mutation"
        builderConfig:
          inputType: "deleteCommentInput"
          payloadType: "deleteCommentPayload"
          mutateAndGetPayload: "@=mutation('delete_comment', [value])"
