Mutation:
  type: object
  config:
    description: "The Root Mutation type."
    fields:
      # Create a user field
      createUser:
        description: "Create a User."
        builder: "Relay::Mutation"
        builderConfig:
          inputType: "createUserInput"
          payloadType: "userPayload"
          mutateAndGetPayload: "@=mutation('create_user', [value])"
      # Update a user field
      updateUser:
        description: "Update a User."
        builder: "Relay::Mutation"
        builderConfig:
          inputType: "updateUserInput"
          payloadType: "userPayload"
          mutateAndGetPayload: "@=mutation('update_user', [value])"
      # Delete a user field
      deleteUser:
        description: "Delete a User."
        builder: "Relay::Mutation"
        builderConfig:
          inputType: "deleteUserInput"
          payloadType: "deleteUserPayload"
          mutateAndGetPayload: "@=mutation('delete_user', [value])"

      # Create a single shirt
      createShirt:
        description: "Create a Shirt."
        builder: "Relay::Mutation"
        builderConfig:
          inputType: "createShirtInput"
          payloadType: "shirtPayload"
          mutateAndGetPayload: "@=mutation('create_shirt', [value])"
      # Update a single shirt
      updateShirt:
        description: "Update a Shirt."
        builder: "Relay::Mutation"
        builderConfig:
          inputType: "updateShirtInput"
          payloadType: "shirtPayload"
          mutateAndGetPayload: "@=mutation('update_shirt', [value])"
