Query:
  type: object
  config:
    description: "The Root Query type."
    fields:
      node:
        builder: Relay::Node
        builderConfig:
          nodeInterfaceType: Node
          idFetcher: '@=resolver("node", [value])'
      # Access a single user field
      user:
        type: "User"
        description: "Access a single User."
        args:
          id:
            type: "ID"
          username:
            type: "String"
        resolve: "@=resolver('get_user', [args])"
      # Get a list of users field
      users:
        type: "UserConnection"
        description: "Get a list of users"
        argsBuilder: "Relay::ForwardConnection"
        resolve: "@=resolver('get_users', [args])"
      # Access a single shirt field
      shirt:
        type: "Shirt"
        description: "Access a single Shirt."
        args:
          id:
            type: "ID"
          slug:
            type: "String"
        resolve: "@=resolver('get_shirt', [args])"
      # Get a list of shirts field
      shirts:
        type: "ShirtConnection"
        description: "Get a list of shirts"
        argsBuilder: "Relay::Connection"
        resolve: "@=resolver('get_shirts', [args])"
      # Access a single comment field
      comment:
        type: "Comment"
        description: "Access a single Comment."
        args:
          id:
            type: "ID!"
        resolve: "@=resolver('get_comment', [args['id']])"
      # Get a list of comments field
      comments:
        type: "CommentConnection"
        description: "Get a list of comments"
        argsBuilder: "Relay::ForwardConnection"
        resolve: "@=resolver('get_comments', [args])"
