LoginInput:
  type: relay-mutation-input
  config:
    fields:
      username:
        type: "String"
      email:
        type: "String"
      password:
        type: "String!"

logoutPayload:
  type: object
  config:
    fields:
      clientMutationId:
        type: "String!"

logoutInput:
  type: input-object
  config:
    fields:
      clientMutationId:
        type: "String!"
