Shirt:
  type: object
  config:
    description: "The Shirt type."
    fields:
      id:
        type: "ID!"
      title:
        type: "String!"
      slug:
        type: "String!"
      description:
        type: "String"
      front_path:
        type: "String!"
      back_path:
        type: "String!"
      published_date:
        type: "DateTime!"
      author:
        type: "User"
    interfaces: ["Node"]

ShirtConnection:
  type: relay-connection
  config:
    nodeType: "Shirt"
    connectionFields:
      totalCount:
        type: "Int!"
