Shirt:
  type: object
  config:
    description: "The Shirt type."
    fields:
      id:
        type: "ID!"
      title:
        type: "String!"
      slug:
        type: "String!"
      description:
        type: "String"
      front_path:
        type: "String!"
      back_path:
        type: "String!"
      published_date:
        type: "DateTime!"
      author:
        type: "User"
    interfaces: ["Node"]

ShirtConnection:
  type: relay-connection
  config:
    nodeType: "Shirt"
    connectionFields:
      totalCount:
        type: "Int!"

shirtPayload:
  type: relay-mutation-payload
  config:
    fields:
      id:
        type: "ID!"
      title:
        type: "String!"
      slug:
        type: "String!"
      description:
        type: "String"
      front_path:
        type: "String!"
      back_path:
        type: "String!"
      published_date:
        type: "DateTime!"
      author:
        type: "User"

createShirtInput:
  type: relay-mutation-input
  config:
    fields:
      title:
        type: "String!"
      description:
        type: "String"
      front_path:
        type: "String!"
      back_path:
        type: "String!"

updateShirtInput:
  type: relay-mutation-input
  config:
    fields:
      id:
        type: "ID!"
      title:
        type: "String"
      description:
        type: "String"
      front_path:
        type: "String"
      back_path:
        type: "String"

deleteShirtPayload:
  type: relay-mutation-payload
  config:
    fields:
      id:
        type: "ID!"

deleteShirtInput:
  type: relay-mutation-input
  config:
    fields:
      id:
        type: "ID"
      slug:
        type: "String"
