User:
  type: object
  config:
    description: "The User type."
    fields:
      id:
        type: "ID!"
      username:
        type: "String!"
    interfaces: ["Node"]

UserConnection:
  type: relay-connection
  config:
    nodeType: "User"
    connectionFields:
      totalCount:
        type: "Int!"

userPayload:
  type: relay-mutation-payload
  config:
    fields:
      id:
        type: "ID!"
      username:
        type: "String!"

createUserInput:
  type: relay-mutation-input
  config:
    fields:
      username:
        type: "String!"
      email:
        type: "String!"
      password:
        type: "String!"
