User:
  type: object
  config:
    description: "The User type."
    fields:
      id:
        type: "ID!"
      username:
        type: "String!"
    interfaces: ["Node"]

UserConnection:
  type: relay-connection
  config:
    nodeType: "User"
    connectionFields:
      totalCount:
        type: "Int!"
